" Pro tip for MacVim on retina displays: Get the sexy font rendering used by Termial.app/iTerm:
" defaults write org.vim.MacVim AppleFontSmoothing -int 0

" Command-Shift-F is fullscreen.
nmap <D-F> :set fullscreen!<CR>

augroup _gvimrc
  autocmd!

  " Gutter color default is annoying. Make it blend in.
  autocmd ColorScheme * hi SignColumn guibg=NONE

  " FZF uses ctermfg for some colors. Ew.
  autocmd ColorScheme * hi Number ctermfg=7
  autocmd ColorScheme * hi Conditional ctermfg=7
  autocmd ColorScheme * hi Special ctermfg=7

augroup END

let g:one_allow_italics = 1

let g:nord_italic_comments = 1
let g:nord_uniform_status_lines = 1
colorscheme nord

hi link ALEWarningSign WarningMsg
hi link ALEErrorSign ErrorMsg
let g:lightline.colorscheme = 'nord'
call g:lightline#init()

" 99% as good as PragmataPro, 100% free! Ligatures are kinda cute, too.
set guifont=Iosevka:h16

set columns=80 lines=50
set errorbells
set guicursor+=a:blinkon0
set guioptions=igm
set mousemodel=popup
set cursorline
set nonumber
set scrolloff=15
set sidescrolloff=6
set visualbell

if has("gui_macvim")
  set title titlestring=MacVim\ \|\ %{substitute(getcwd(),\ $HOME,\ '~',\ '')}
  set fuoptions=maxhorz,maxvert
  set transparency=0
  set macthinstrokes
  set macligatures
elseif has("gui")
  set title titlestring=gvim\ \|\ %{substitute(getcwd(),\ $HOME,\ '~',\ '')}
end

" Now load specifics to this machine.
if filereadable(expand("~/.gvimlocal"))
  source ~/.gvimlocal
endif
