" Pro tip for MacVim on retina displays: Get the sexy font rendering used by Termial.app/iTerm:
" defaults write org.vim.MacVim AppleFontSmoothing -int 0

" Gutter color default is annoying. Make it blend in.
hi SignColumn guibg=NONE

hi Search term=NONE ctermfg=0 ctermbg=14 guifg=#ffffff guibg=#444444

" FZF uses ctermfg for some colors. Ew.
hi Number ctermfg=7
hi Conditional ctermfg=7
hi Special ctermfg=7

" Command-Shift-F is fullscreen.
nmap <D-F> :set fullscreen!<CR>

let g:nord_italic_comments = 1
let g:nord_uniform_status_lines = 1
let g:nord_comment_brightness = 15
colorscheme nord
hi link ALEWarningSign WarningMsg
hi link ALEErrorSign ErrorMsg
let g:lightline.colorscheme = 'nord'
call g:lightline#init()
set guifont=Essential\ PragmataPro:h14

set columns=80 lines=50
set errorbells
set fuoptions=maxhorz,maxvert
set guicursor+=a:blinkon0
set guioptions=igm
set mousemodel=popup
set nocursorline
set nonumber
set scrolloff=15
set sidescrolloff=6
set title titlestring=Vim\ —\ %{substitute(getcwd(),\ $HOME,\ '~',\ '')}
set transparency=0
set visualbell

" Now load specifics to this machine.
if filereadable(expand("~/.gvimlocal"))
  source ~/.gvimlocal
endif
